---
- name: install apache
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - apache2
    - apache2-utils
  update_cache: true

#- name: enable mod_rewrite for wordpress
#  apache2_module:
#    state: present
#    name: rewrite
#
#- name: enable the use of .htaccess files 
#  copy:
#    src: enable_htaccess.conf
#    dest: /etc/apache2/sites-available/enable_htaccess.conf
#
#- name: enable the .htaccess vhost
#  file:
#    src: /etc/apache2/sites-available/enable_htaccess.conf
#    dest: /etc/apache2/sites-enabled/enable_htaccess.conf
#    state: link
# 
