---
 
  - name: Install MySQL Python
    apt:
      name: python-mysqldb
      state: present
 
  - name: install MySQL Server
    apt:
      name: mysql-server
      state: present
 
  - name: install MySQL Client
    apt:
      name: mysql-client
      state: present
 
  - name: install MySQL Common
    apt:
      name: mysql-common
      state: present
 
  - name: ensure MySQL always starts
    service:
      name: mysql
      state: started
      enabled: yes
