---
- name: create rds
  rds:
    command: create
    instance_name: "{{rds_instance_id}}"
    db_engine: MySQL
    size: 10
    aws_access_key: "{{access_key}}"
    aws_secret_key: "{{secret_key}}"
    region: "{{region}}"
    instance_type: db.t2.small
    db_name: "{{db_name}}"
    username: "{{db_user}}"
    password: "{{db_pass}}"
    wait: yes
#    db_security_groups:
#      - "{{rds_sg}}"
    wait_timeout: 900   #wait till rds is created and return the endpoint
  register: rds
